
DROP TABLE PAYMENT CASCADE CONSTRAINTS PURGE;



DROP TABLE CONTRACT CASCADE CONSTRAINTS PURGE;



DROP TABLE USER CASCADE CONSTRAINTS PURGE;



DROP TABLE ROOM CASCADE CONSTRAINTS PURGE;



DROP TABLE BUILDING CASCADE CONSTRAINTS PURGE;



DROP TABLE COM_TYPE CASCADE CONSTRAINTS PURGE;



CREATE TABLE COM_TYPE
(
	TYPE_CD               VARCHAR2(3)  NOT NULL ,
	TYPE_NM               VARCHAR2(20)  NULL ,
	COM_CD                VARCHAR2(3)  NULL ,
	DESCR                 VARCHAR2(50)  NULL ,
CONSTRAINT  COM_TYPE PRIMARY KEY (TYPE_CD)
);



CREATE TABLE BUILDING
(
	BUILDING_ID           VARCHAR2(10)  NOT NULL ,
	NAME                  VARCHAR2(20)  NULL ,
	ADDR                  VARCHAR2(50)  NULL ,
	ADMIN                 VARCHAR2(20)  NULL ,
	REG_DTIME             VARCHAR2(14)  NULL ,
CONSTRAINT  BUILDING PRIMARY KEY (BUILDING_ID)
);



CREATE TABLE ROOM
(
	ROOM_ID               VARCHAR2(10)  NOT NULL ,
	ROOM_TYPE             VARCHAR2(3)  NOT NULL ,
	HO                    VARCHAR2(3)  NOT NULL ,
	BUILDING_ID           VARCHAR2(10)  NOT NULL ,
	REG_DTIME             VARCHAR2(14)  NULL ,
CONSTRAINT  ROOM PRIMARY KEY (ROOM_ID,ROOM_TYPE,HO,BUILDING_ID),
CONSTRAINT  ROOM FOREIGN KEY (BUILDING_ID) REFERENCES BUILDING(BUILDING_ID)
);




CREATE TABLE USER
(
	USER_ID               VARCHAR2(10)  NOT NULL ,
	USER_KEY              VARCHAR2(20)  NOT NULL ,
	USER_TYPE             VARCHAR2(3)  NOT NULL ,
	NAME                  VARCHAR2(20)  NULL ,
	ADDR                  VARCHAR2(50)  NULL ,
	TEL                   VARCHAR2(50)  NULL ,
	TEL2                  VARCHAR2(50)  NULL ,
	REG_DTIME             VARCHAR2(14)  NULL ,
CONSTRAINT  USER PRIMARY KEY (USER_ID,USER_KEY,USER_TYPE)
);



CREATE TABLE CONTRACT
(
	CONTRACT_ID           VARCHAR2(10)  NOT NULL ,
	ROOM_ID               VARCHAR2(10)  NOT NULL ,
	ROOM_TYPE             VARCHAR2(3)  NOT NULL ,
	HO                    VARCHAR2(3)  NOT NULL ,
	BUILDING_ID           VARCHAR2(10)  NOT NULL ,
	USER_ID               VARCHAR2(10)  NOT NULL ,
	USER_KEY              VARCHAR2(20)  NOT NULL ,
	USER_TYPE             VARCHAR2(3)  NOT NULL ,
	DEPOSIT               VARCHAR2(20)  NOT NULL ,
	PAY_DAY               VARCHAR2(3)  NOT NULL ,
	CONTRACT_STARTDATE    VARCHAR2(14)  NULL ,
	CONTRACT_ENDDATE      VARCHAR2(14)  NULL ,
	CONTRACT_PERIOD       VARCHAR2(3)  NULL ,
	REG_DTIME             VARCHAR2(14)  NULL ,
CONSTRAINT  CONTRACT PRIMARY KEY (CONTRACT_ID,ROOM_ID,ROOM_TYPE,HO,BUILDING_ID,USER_ID,USER_KEY,USER_TYPE,DEPOSIT,PAY_DAY),
CONSTRAINT  CONTRACT FOREIGN KEY (ROOM_ID,ROOM_TYPE,HO,BUILDING_ID) REFERENCES ROOM(ROOM_ID,ROOM_TYPE,HO,BUILDING_ID),
CONSTRAINT  CONTRACT FOREIGN KEY (USER_ID,USER_KEY,USER_TYPE) REFERENCES USER(USER_ID,USER_KEY,USER_TYPE)
);


CREATE TABLE PAYMENT
(
	PAYMENT_ID            VARCHAR2(10)  NOT NULL ,
	CONTRACT_ID           VARCHAR2(10)  NOT NULL ,
	ROOM_ID               VARCHAR2(10)  NOT NULL ,
	ROOM_TYPE             VARCHAR2(3)  NOT NULL ,
	HO                    VARCHAR2(3)  NOT NULL ,
	BUILDING_ID           VARCHAR2(10)  NOT NULL ,
	USER_ID               VARCHAR2(10)  NOT NULL ,
	USER_KEY              VARCHAR2(20)  NOT NULL ,
	USER_TYPE             VARCHAR2(3)  NOT NULL ,
	DEPOSIT               VARCHAR2(20)  NOT NULL ,
	PAY_DAY               VARCHAR2(3)  NOT NULL ,
	INNING                VARCHAR2(3)  NOT NULL ,
	REG_DTIME             VARCHAR2(14)  NULL ,
	CHARGE_YN             VARCHAR2(3)  NULL ,
CONSTRAINT  PAYMENT PRIMARY KEY (PAYMENT_ID,CONTRACT_ID,ROOM_ID,ROOM_TYPE,HO,BUILDING_ID,USER_ID,USER_KEY,USER_TYPE,DEPOSIT,PAY_DAY,INNING),
CONSTRAINT  PAYMENT FOREIGN KEY (CONTRACT_ID,ROOM_ID,ROOM_TYPE,HO,BUILDING_ID,USER_ID,USER_KEY,USER_TYPE,DEPOSIT,PAY_DAY) REFERENCES CONTRACT(CONTRACT_ID,ROOM_ID,ROOM_TYPE,HO,BUILDING_ID,USER_ID,USER_KEY,USER_TYPE,DEPOSIT,PAY_DAY)
);

